import { expect, test } from "@playwright/test";

test.describe("sessions", () => {
  test("list renders cards and category filter works", async ({ page }) => {
    await page.goto("/sessions");
    const cards = page.locator(".session-card");
    await expect(cards.first()).toBeVisible();
    const total = await cards.count();
    expect(total).toBeGreaterThanOrEqual(4);

    await page.getByRole("button", { name: "Wellness" }).click();
    await expect(page.locator(".session-cat.cat-wellness").first()).toBeVisible();
    const filtered = await page.locator(".session-card").count();
    expect(filtered).toBeLessThan(total);
  });

  test("live session shows Join Session Now for enrolled members", async ({
    page,
  }) => {
    await page.goto("/sessions");
    await expect(
      page.getByRole("link", { name: "Join Session Now" }),
    ).toBeVisible();
  });

  test("detail page tabs: overview, AI summary on a completed session", async ({
    page,
  }) => {
    await page.goto("/sessions/leading-intention");
    await expect(page.locator(".sess-title")).toContainText(
      "Leading with Intention",
    );
    await page.getByRole("button", { name: "AI Summary" }).click();
    await expect(page.locator(".ai-header-text")).toContainText(
      "Generated by Momentum+ AI",
    );
    await expect(page.locator(".ai-takeaway").first()).toBeVisible();
  });

  test("notes editor autosaves in preview mode", async ({ page }) => {
    await page.goto("/sessions/resilience-rituals");
    await page.getByRole("button", { name: "My Notes" }).click();
    await page.locator(".notes-area").fill("Test note for e2e");
    await expect(page.locator(".notes-status")).toContainText("Saved", {
      timeout: 5_000,
    });
  });

  test("live room gates non-enrolled members to an enroll prompt", async ({
    page,
  }) => {
    // strategic-networking is not enrolled in placeholder data
    await page.goto("/sessions/strategic-networking/live");
    await expect(page.getByText("Enroll to join this session")).toBeVisible();
  });

  test(".ics download endpoint serves a calendar", async ({ request }) => {
    const res = await request.get("/api/sessions/resilience-rituals/ics");
    expect(res.status()).toBe(200);
    expect(res.headers()["content-type"]).toContain("text/calendar");
    const body = await res.text();
    expect(body).toContain("BEGIN:VCALENDAR");
    expect(body).toContain("SUMMARY:Momentum+");
  });
});
