/*
 * AI session summaries (SPEC.md §4): transcript → Claude → structured JSON
 * {takeaways[], quotes[], action_items[], highlights} stored in ai_summaries.
 * Env-gated on ANTHROPIC_API_KEY. Attribution in the UI reads
 * "Generated by Momentum+ AI" per the mockup.
 */

export const SUMMARY_MODEL = "claude-sonnet-5";

export function isAnthropicConfigured(): boolean {
  return Boolean(process.env.ANTHROPIC_API_KEY);
}

export interface GeneratedSummary {
  takeaways: string[];
  quotes: string[];
  action_items: string[];
  highlights: string;
}

const SYSTEM_PROMPT = `You summarize leadership development session transcripts for Momentum+, a national members-only community for business leaders. Voice: confident, plain-spoken, practical — never motivational-poster language, no emoji.

Return ONLY a JSON object with exactly these keys:
- "takeaways": 3-5 short, concrete lessons a member can apply (strings)
- "quotes": 1-3 verbatim, quotable lines from the speaker (strings)
- "action_items": 2-4 specific things a member should do this week (strings)
- "highlights": one 1-2 sentence overview of the session (string)`;

/**
 * Extract the JSON object from a model response that may wrap it in prose or
 * code fences. Pure — unit-tested.
 */
export function parseSummaryResponse(text: string): GeneratedSummary | null {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end <= start) return null;
  try {
    const obj = JSON.parse(text.slice(start, end + 1)) as Record<string, unknown>;
    const arr = (v: unknown): string[] =>
      Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : [];
    const summary: GeneratedSummary = {
      takeaways: arr(obj.takeaways),
      quotes: arr(obj.quotes),
      action_items: arr(obj.action_items),
      highlights: typeof obj.highlights === "string" ? obj.highlights : "",
    };
    if (summary.takeaways.length === 0 && !summary.highlights) return null;
    return summary;
  } catch {
    return null;
  }
}

export async function generateSummary(
  transcript: string,
  sessionTitle: string,
  speakerName: string,
): Promise<GeneratedSummary | null> {
  const { getAnthropicApiKey } = await import("./service-config");
  const apiKey = await getAnthropicApiKey();
  if (!apiKey) return null;

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "content-type": "application/json",
    },
    body: JSON.stringify({
      model: SUMMARY_MODEL,
      max_tokens: 2048,
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: "user",
          content: `Session: "${sessionTitle}" with ${speakerName}\n\nTranscript:\n${transcript.slice(0, 150_000)}`,
        },
      ],
    }),
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error(`Anthropic API failed: ${res.status} ${await res.text()}`);
  }
  const json = (await res.json()) as {
    content: { type: string; text?: string }[];
  };
  const text = json.content.find((b) => b.type === "text")?.text ?? "";
  return parseSummaryResponse(text);
}
