// GENERATED by scripts/sync-db-selects.mjs — do not edit by hand.
// Run `npm run selects:sync` after changing any select that embeds a
// related table. tests/db-selects.test.ts fails when this file is stale.
//
// Every embedded select the app performs. lib/health.ts runs each one against
// the database every 6 hours, so a query that stops resolving is reported
// instead of waiting to be discovered by whoever loads the page.

export interface ProbedSelect {
  table: string;
  select: string;
}

export const PROBED_SELECTS: ProbedSelect[] = [
  // app/(portal)/admin/education/actions.ts
  { table: "course_lessons", select: "title, summary, content, video_id, courses ( title )" },
  // lib/education.ts
  { table: "courses", select: "id, title, description, category, min_access, ce_hours, published_at, course_lessons ( id )" },
  // lib/education.ts
  { table: "courses", select: "id, title, description, category, min_access, published_at, ce_hours, course_lessons ( id, title, summary, video_id, position, content, image_url, documents )" },
  // app/(portal)/admin/education/page.tsx
  { table: "courses", select: "id, title, description, category, min_access, published_at, ce_hours, course_lessons ( id, title, summary, video_id, position, content, image_url, documents, quiz )" },
  // lib/activity.ts
  { table: "enrollments", select: "created_at, attended, profiles ( full_name, email ), sessions ( title )" },
  // lib/attendance.ts
  { table: "enrollments", select: "id, profile_id, profiles ( email, full_name )" },
  // app/(portal)/speaker/actions.ts
  { table: "enrollments", select: "profile_id, profiles ( email, full_name )" },
  // app/api/cron/reminders/route.ts
  { table: "enrollments", select: "profile_id, profiles ( email, full_name, phone )" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "enrollments", select: "session_id, attended, profiles ( full_name, email )" },
  // app/(portal)/layout.tsx
  { table: "enrollments", select: "sessions ( id, title, starts_at, status )" },
  // app/(portal)/layout.tsx
  { table: "enrollments", select: "sessions ( id, title, starts_at, status, duration_min, recurrence, recurrence_until )" },
  // lib/activity.ts
  { table: "lesson_progress", select: "completed_at, profiles ( full_name, email ), course_lessons ( title, courses ( title ) )" },
  // lib/activity.ts
  { table: "memberships", select: "created_at, tier, source, profiles ( full_name, email )" },
  // app/api/cron/dunning/route.ts
  { table: "memberships", select: "id, dunning_notices ( membership_id )" },
  // app/api/cron/dunning/route.ts
  { table: "memberships", select: "id, profile_id, ghl_contact_id, profiles ( email, full_name ), dunning_notices ( step, sent_at )" },
  // lib/announcements-delivery.ts
  { table: "memberships", select: "profile_id, ghl_contact_id, profiles ( email, full_name, phone )" },
  // app/(portal)/admin/announcements/actions.ts
  { table: "memberships", select: "profile_id, profiles ( phone )" },
  // lib/directory-queries.ts
  { table: "memberships", select: "profiles ( full_name )" },
  // lib/podcast.ts
  { table: "podcast_questions", select: "id, kind, body, status, created_at, profiles(full_name, email)" },
  // app/(portal)/admin/members/actions.ts
  { table: "profiles", select: "id, admin_role, memberships ( tier, status )" },
  // app/(portal)/admin/members/page.tsx
  { table: "profiles", select: "id, full_name, email, title, company, phone, admin_role, admin_perms, memberships!inner ( id, tier, status, access_expires_at, source, created_at )" },
  // app/(portal)/members/page.tsx
  { table: "profiles", select: "id, full_name, title, company, industry, email, phone, share_contact, memberships!inner(tier, status)" },
  // app/(portal)/search/page.tsx
  { table: "profiles", select: "id, full_name, title, company, industry, memberships!inner(tier, status)" },
  // lib/activity.ts
  { table: "resource_uses", select: "used_at, profiles ( full_name, email ), resources ( title )" },
  // lib/sessions/queries.ts
  { table: "session_speakers", select: "session_id, sort, speakers!session_speakers_speaker_id_fkey ( id, name, title )" },
  // app/api/zoom/signature/route.ts
  { table: "sessions", select: "id, starts_at, duration_min, status, recurrence, recurrence_until, zoom_meeting_id, zoom_passcode, speakers!sessions_speaker_id_fkey ( profile_id, archived_at, expires_at )" },
  // app/api/cron/summaries/route.ts
  { table: "sessions", select: "id, title, ai_summaries ( id )" },
  // lib/sessions/queries.ts
  { table: "sessions", select: "id, title, description, category, starts_at, duration_min, capacity, min_access, status, program, recurrence, recurrence_until, host_name, restricted, speakers!sessions_speaker_id_fkey ( id, name, title, archived_at, expires_at )" },
  // lib/sessions/queries.ts
  { table: "sessions", select: "id, title, description, category, starts_at, duration_min, capacity, min_access, status, program, recurrence, recurrence_until, host_name, speakers!sessions_speaker_id_fkey ( id, name, title, archived_at, expires_at )" },
  // lib/sessions/queries.ts
  { table: "sessions", select: "id, title, description, category, starts_at, duration_min, capacity, min_access, status, speakers!sessions_speaker_id_fkey ( id, name, title )" },
  // app/(portal)/admin/topics/page.tsx
  { table: "sessions", select: "id, title, host_name, session_topics ( topic_id, is_primary ), speakers!sessions_speaker_id_fkey ( name )" },
  // app/api/cron/summaries/route.ts
  { table: "sessions", select: "id, title, speakers!sessions_speaker_id_fkey ( name )" },
  // app/page.tsx
  { table: "sessions", select: "id, title, starts_at, speakers!sessions_speaker_id_fkey ( name )" },
  // lib/activity.ts
  { table: "sponsor_events", select: "at, kind, profiles ( full_name, email ), sponsors ( name )" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsor_members", select: "profile_id, sponsors!inner ( archived_at, expires_at )" },
  // app/(portal)/admin/sponsors/page.tsx
  { table: "sponsor_members", select: "sponsor_id, profile_id, profiles ( full_name, email )" },
  // app/(portal)/sponsor/actions.ts
  { table: "sponsor_members", select: "sponsor_id, sponsors!inner ( archived_at, expires_at )" },
  // app/expired/page.tsx
  { table: "sponsor_members", select: "sponsors ( name, expires_at, archived_at )" },
  // lib/activity.ts
  { table: "video_views", select: "watched_at, profiles ( full_name, email ), videos ( title )" },
  // app/(portal)/speaker/actions.ts
  { table: "videos", select: "id, session_id, sessions!inner ( speaker_id )" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, mux_playback_id, thumbnail_url, duration_sec, min_access, published_at, session_id, sessions ( speakers!sessions_speaker_id_fkey ( name ) )" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, mux_playback_id, thumbnail_url, duration_sec, min_access, published_at, session_id, sessions ( speakers!sessions_speaker_id_fkey ( name ), ai_summaries ( takeaways, quotes, action_items, highlights, model, generated_at ) ), ai_summaries!video_id ( takeaways, quotes, action_items, highlights, model, generated_at )" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, season, video_topics ( is_primary, content_topics ( id, name, slug ) ), mux_playback_id, thumbnail_url, duration_sec, min_access, published_at, session_id, sessions ( speakers!sessions_speaker_id_fkey ( name ) )" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, season, video_topics ( is_primary, content_topics ( id, name, slug ) ), mux_playback_id, thumbnail_url, duration_sec, min_access, published_at, session_id, sessions ( speakers!sessions_speaker_id_fkey ( name ), ai_summaries ( takeaways, quotes, action_items, highlights, model, generated_at ) ), ai_summaries!video_id ( takeaways, quotes, action_items, highlights, model, generated_at )" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, season, video_topics ( is_primary, content_topics ( id, name, slug ) ), thumbnail_url, duration_sec, min_access, published_at, sessions ( speakers!sessions_speaker_id_fkey ( name ) )" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, thumbnail_url, duration_sec, min_access, published_at, sessions ( speakers!sessions_speaker_id_fkey ( name ) )" },
  // app/api/cron/summaries/route.ts
  { table: "videos", select: "id, title, min_access, mux_playback_id, published_at, session_id, ai_summaries!video_id ( id ), sessions ( ai_summaries ( id ) )" },
  // app/api/cron/summaries/route.ts
  { table: "videos", select: "id, title, mux_asset_id, mux_playback_id, duration_sec, published_at, session_id, ai_summaries!video_id ( id ), sessions ( ai_summaries ( id ) )" },
  // app/(portal)/admin/topics/page.tsx
  { table: "videos", select: "id, title, session_id, video_topics ( topic_id, is_primary ), sessions ( speakers!sessions_speaker_id_fkey ( name ) )" },
  // app/(portal)/admin/education/actions.ts
  { table: "videos", select: "title, session_id, ai_summaries!video_id ( takeaways, quotes, action_items, highlights )" },
];
