// GENERATED by scripts/sync-db-selects.mjs — do not edit by hand.
// Run `npm run selects:sync` after changing any select.
// tests/db-selects.test.ts fails when this file is stale.
//
// Every select the app performs. lib/health.ts runs each one against the
// database every 6 hours, so a query that stops resolving is reported
// instead of waiting to be discovered by whoever loads the page.

export interface ProbedSelect {
  table: string;
  select: string;
}

export const PROBED_SELECTS: ProbedSelect[] = [
  // lib/throttle.ts
  { table: "action_events", select: "id" },
  // lib/ads.ts
  { table: "ad_placements", select: "key, label, description, sort" },
  // lib/admin-audit.ts
  { table: "admin_audit_log", select: "actor_email, action, target_email, detail, at" },
  // lib/onboarding.ts
  { table: "admin_audit_log", select: "id" },
  // app/(portal)/admin/ads/page.tsx
  { table: "ads", select: "id" },
  // lib/ads.ts
  { table: "ads", select: "id, placement_key, kind, title, body, cta_label, url, image_url, sponsor_id, sort, active, starts_at, ends_at" },
  // lib/ads.ts
  { table: "ads", select: "id, placement_key, kind, title, body, cta_label, url, image_url, sponsor_id, sort, active, starts_at, ends_at, tiers" },
  // app/(portal)/admin/ads/actions.ts
  { table: "ads", select: "id, placement_key, sort" },
  // app/(portal)/admin/ads/actions.ts
  { table: "ads", select: "id, sort" },
  // app/(portal)/admin/ads/actions.ts
  { table: "ads", select: "sort" },
  // lib/speaker-tools.ts
  { table: "advisor_agreements", select: "agreement_version, signed_name, signed_at, phone, organization" },
  // app/(portal)/admin/speakers/page.tsx
  { table: "advisor_agreements", select: "speaker_id, agreement_version, signed_at" },
  // lib/advisor-intake-db.ts
  { table: "advisor_intake", select: "speaker_id, submitted_at, updated_at" },
  // lib/agreement-doc-db.ts
  { table: "agreement_overrides", select: "sections, note, material_changed_at" },
  // app/(portal)/admin/agreement/page.tsx
  { table: "agreement_overrides", select: "speaker_id, sections, note" },
  // lib/agreement-doc-db.ts
  { table: "agreement_templates", select: "id, version, title, preamble, acceptance, sections" },
  // lib/agreement-doc-db.ts
  { table: "agreement_templates", select: "material_changed_at" },
  // lib/agreement-doc-db.ts
  { table: "agreement_templates", select: "version, title, preamble, acceptance, sections, material_changed_at" },
  // app/(portal)/admin/education/actions.ts
  { table: "ai_summaries", select: "takeaways, quotes, action_items, highlights" },
  // lib/announcements-delivery.ts
  { table: "announcement_deliveries", select: "profile_id, notified_at, emailed_at" },
  // lib/announcements-delivery.ts
  { table: "announcement_deliveries", select: "profile_id, sms_at" },
  // app/(portal)/admin/announcements/actions.ts
  { table: "announcements", select: "id" },
  // lib/announcements-delivery.ts
  { table: "announcements", select: "id, title, body, audience_tiers, channels, community_posted_at" },
  // app/(portal)/admin/announcements/page.tsx
  { table: "announcements", select: "id, title, send_at, audience_tiers, channels" },
  // app/(portal)/admin/announcements/page.tsx
  { table: "announcements", select: "id, title, sent_at, audience_tiers" },
  // lib/activity.ts
  { table: "announcements", select: "sent_at, title" },
  // lib/tiers.ts
  { table: "app_features", select: "key, label, description, nav_href, sort, is_launched" },
  // app/api/health/route.ts
  { table: "app_settings", select: "key" },
  // app/api/cron/monthly-report/route.ts
  { table: "app_settings", select: "value" },
  // lib/topics.ts
  { table: "content_topics", select: "id, name, slug, description, sort" },
  // app/(portal)/admin/education/actions.ts
  { table: "course_lessons", select: "documents" },
  // lib/badge-queries.ts
  { table: "course_lessons", select: "id, course_id" },
  // app/(portal)/admin/education/actions.ts
  { table: "course_lessons", select: "id, course_id, position" },
  // app/(portal)/admin/education/actions.ts
  { table: "course_lessons", select: "id, position" },
  // lib/education.ts
  { table: "course_lessons", select: "id, quiz" },
  // app/(portal)/admin/education/actions.ts
  { table: "course_lessons", select: "position" },
  // app/(portal)/education/actions.ts
  { table: "course_lessons", select: "quiz" },
  // app/(portal)/admin/education/actions.ts
  { table: "course_lessons", select: "title, summary, content, video_id, courses ( title )" },
  // app/(portal)/admin/education/actions.ts
  { table: "courses", select: "id" },
  // lib/education.ts
  { table: "courses", select: "id, title, description, category, min_access, ce_hours, published_at, course_lessons ( id )" },
  // lib/education.ts
  { table: "courses", select: "id, title, description, category, min_access, published_at, ce_hours, course_lessons ( id, title, summary, video_id, position, content, image_url, documents )" },
  // app/(portal)/admin/education/page.tsx
  { table: "courses", select: "id, title, description, category, min_access, published_at, ce_hours, course_lessons ( id, title, summary, video_id, position, content, image_url, documents, quiz )" },
  // app/(portal)/admin/education/actions.ts
  { table: "courses", select: "published_at" },
  // app/api/cron/monthly-report/route.ts
  { table: "email_events", select: "id" },
  // app/(portal)/admin/email-activity/page.tsx
  { table: "email_events", select: "id, email, event, reason, occurred_at" },
  // lib/sessions/queries.ts
  { table: "enrollments", select: "attended" },
  // lib/activity.ts
  { table: "enrollments", select: "enrolled_at, attended, profiles ( full_name, email ), sessions ( title )" },
  // lib/sessions/queries.ts
  { table: "enrollments", select: "id" },
  // lib/attendance.ts
  { table: "enrollments", select: "id, profile_id, profiles ( email, full_name )" },
  // lib/badge-queries.ts
  { table: "enrollments", select: "profile_id" },
  // app/(portal)/speaker/actions.ts
  { table: "enrollments", select: "profile_id, profiles ( email, full_name )" },
  // app/api/cron/reminders/route.ts
  { table: "enrollments", select: "profile_id, profiles ( email, full_name, phone )" },
  // app/api/zoom/signature/route.ts
  { table: "enrollments", select: "session_id" },
  // app/api/cron/monthly-report/route.ts
  { table: "enrollments", select: "session_id, attended" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "enrollments", select: "session_id, attended, profiles ( full_name, email )" },
  // app/(portal)/layout.tsx
  { table: "enrollments", select: "sessions ( id, title, starts_at, status )" },
  // app/(portal)/layout.tsx
  { table: "enrollments", select: "sessions ( id, title, starts_at, status, duration_min, recurrence, recurrence_until )" },
  // lib/error-reports.ts
  { table: "error_report_hits", select: "hash" },
  // app/api/errors/route.ts
  { table: "error_report_hits", select: "hits" },
  // app/(portal)/admin/errors/actions.ts
  { table: "error_report_hits", select: "profile_id" },
  // lib/health.ts
  { table: "error_reports", select: "hash" },
  // app/(portal)/branching-out/actions.ts
  { table: "error_reports", select: "hash, count" },
  // app/api/errors/route.ts
  { table: "error_reports", select: "hash, count, last_emailed_at" },
  // lib/error-reports.ts
  { table: "error_reports", select: "hash, message, path, count, first_seen, last_seen, users_notified_at" },
  // app/api/errors/route.ts
  { table: "error_reports", select: "last_emailed_at" },
  // app/api/webhooks/ghl/route.ts
  { table: "ghl_webhook_events", select: "id, received_at" },
  // app/api/import/tsls/route.ts
  { table: "import_log", select: "id" },
  // app/(portal)/education/[id]/certificate/page.tsx
  { table: "lesson_progress", select: "completed_at" },
  // lib/activity.ts
  { table: "lesson_progress", select: "completed_at, profiles ( full_name, email ), course_lessons ( title, courses ( title ) )" },
  // lib/education.ts
  { table: "lesson_progress", select: "lesson_id" },
  // app/(portal)/profile/page.tsx
  { table: "lesson_progress", select: "lesson_id, completed_at" },
  // lib/badge-queries.ts
  { table: "lesson_progress", select: "profile_id, lesson_id" },
  // app/(portal)/admin/control-center/actions.ts
  { table: "member_tiers", select: "slug" },
  // lib/revenue.ts
  { table: "member_tiers", select: "slug, counts_toward_speaker_pay" },
  // lib/tiers.ts
  { table: "member_tiers", select: "slug, label, description, rank, is_builtin, is_public, went_live_at, clears_vip_plus, clears_pro_only, library_scope, counts_toward_speaker_pay, archived_at" },
  // app/(portal)/admin/control-center/actions.ts
  { table: "member_tiers", select: "slug, label, is_builtin" },
  // app/(portal)/admin/control-center/actions.ts
  { table: "member_tiers", select: "slug, label, went_live_at" },
  // app/(portal)/admin/members/actions.ts
  { table: "memberships", select: "access_expires_at" },
  // lib/activity.ts
  { table: "memberships", select: "created_at, tier, source, profiles ( full_name, email )" },
  // app/(portal)/community/actions.ts
  { table: "memberships", select: "ghl_contact_id" },
  // app/(auth)/speaker-onboarding/actions.ts
  { table: "memberships", select: "id" },
  // app/api/webhooks/stripe/route.ts
  { table: "memberships", select: "id, access_expires_at" },
  // app/api/cron/dunning/route.ts
  { table: "memberships", select: "id, dunning_notices ( membership_id )" },
  // app/api/cron/reconcile/route.ts
  { table: "memberships", select: "id, ghl_contact_id" },
  // app/api/cron/dunning/route.ts
  { table: "memberships", select: "id, profile_id, ghl_contact_id, profiles ( email, full_name ), dunning_notices ( step, sent_at )" },
  // app/(portal)/profile/billing-actions.ts
  { table: "memberships", select: "id, status" },
  // lib/sponsor-membership.ts
  { table: "memberships", select: "id, tier" },
  // app/(portal)/admin/members/actions.ts
  { table: "memberships", select: "id, tier, status, access_expires_at" },
  // lib/onboarding.ts
  { table: "memberships", select: "id, tier, status, access_expires_at, source, stripe_subscription_id" },
  // app/api/webhooks/ghl/route.ts
  { table: "memberships", select: "id, tier, status, access_starts_at, access_expires_at" },
  // app/(portal)/admin/members/page.tsx
  { table: "memberships", select: "profile_id" },
  // app/(portal)/admin/errors/actions.ts
  { table: "memberships", select: "profile_id, ghl_contact_id" },
  // lib/announcements-delivery.ts
  { table: "memberships", select: "profile_id, ghl_contact_id, profiles ( email, full_name, phone )" },
  // app/(portal)/admin/announcements/actions.ts
  { table: "memberships", select: "profile_id, profiles ( phone )" },
  // lib/sponsor-team.ts
  { table: "memberships", select: "profile_id, status, access_expires_at" },
  // lib/engagement-notify.ts
  { table: "memberships", select: "profile_id, tier" },
  // lib/revenue.ts
  { table: "memberships", select: "profile_id, tier, source" },
  // lib/badge-queries.ts
  { table: "memberships", select: "profile_id, tier, status, access_starts_at, created_at" },
  // lib/directory-queries.ts
  { table: "memberships", select: "profiles ( full_name )" },
  // app/(portal)/admin/members/actions.ts
  { table: "memberships", select: "stripe_subscription_id" },
  // app/(portal)/admin/control-center/page.tsx
  { table: "memberships", select: "tier" },
  // app/(portal)/profile/billing-actions.ts
  { table: "memberships", select: "tier, access_expires_at" },
  // app/(portal)/admin/members/actions.ts
  { table: "memberships", select: "tier, profile_id" },
  // app/(portal)/admin/members/actions.ts
  { table: "memberships", select: "tier, profile_id, source, access_expires_at" },
  // app/(portal)/profile/page.tsx
  { table: "memberships", select: "tier, status, access_expires_at" },
  // lib/current-member.ts
  { table: "memberships", select: "tier, status, access_starts_at, access_expires_at" },
  // app/(portal)/dashboard/page.tsx
  { table: "notification_prefs", select: "key" },
  // app/(portal)/profile/page.tsx
  { table: "notification_prefs", select: "key, email, sms, in_app" },
  // app/(portal)/admin/announcements/actions.ts
  { table: "notification_prefs", select: "profile_id" },
  // app/api/cron/reminders/route.ts
  { table: "notification_prefs", select: "profile_id, email, sms, in_app" },
  // lib/announcements-delivery.ts
  { table: "notification_prefs", select: "profile_id, in_app" },
  // app/api/cron/reconcile/route.ts
  { table: "notifications", select: "id" },
  // app/(portal)/layout.tsx
  { table: "notifications", select: "id, title, body, link, read_at, created_at" },
  // app/(portal)/speaker/actions.ts
  { table: "notifications", select: "profile_id" },
  // app/(portal)/branching-out/actions.ts
  { table: "podcast_episode_progress", select: "completed, completed_at" },
  // lib/podcast.ts
  { table: "podcast_episode_progress", select: "episode_id, completed, notes" },
  // lib/badge-queries.ts
  { table: "podcast_episode_progress", select: "profile_id" },
  // lib/podcast.ts
  { table: "podcast_episodes", select: "*" },
  // app/(portal)/admin/podcast/actions.ts
  { table: "podcast_episodes", select: "id" },
  // lib/podcast.ts
  { table: "podcast_episodes", select: "id, youtube_video_id, published_at" },
  // lib/podcast.ts
  { table: "podcast_episodes", select: "id, youtube_video_id, title, published_at, season" },
  // lib/podcast.ts
  { table: "podcast_episodes", select: "id, youtube_video_id, title, show_notes, published_at, source" },
  // lib/podcast.ts
  { table: "podcast_episodes", select: "youtube_video_id" },
  // lib/podcast.ts
  { table: "podcast_questions", select: "id, kind, body, status, created_at, profiles(full_name, email)" },
  // app/rescue/page.tsx
  { table: "profiles", select: "admin_role" },
  // lib/auth-helpers.ts
  { table: "profiles", select: "admin_role, admin_perms" },
  // app/(portal)/dashboard/page.tsx
  { table: "profiles", select: "created_at" },
  // app/(portal)/admin/members/actions.ts
  { table: "profiles", select: "email" },
  // app/(portal)/admin/members/actions.ts
  { table: "profiles", select: "email, stripe_customer_id" },
  // app/(portal)/community/actions.ts
  { table: "profiles", select: "full_name" },
  // app/(auth)/welcome/page.tsx
  { table: "profiles", select: "full_name, company, title, phone, industry, bio" },
  // app/(portal)/admin/sponsors/page.tsx
  { table: "profiles", select: "full_name, email" },
  // lib/current-member.ts
  { table: "profiles", select: "full_name, email, admin_title, admin_role" },
  // lib/current-member.ts
  { table: "profiles", select: "full_name, email, admin_title, admin_role, tester" },
  // app/(portal)/profile/billing-actions.ts
  { table: "profiles", select: "full_name, email, stripe_customer_id" },
  // app/(portal)/admin/control-center/page.tsx
  { table: "profiles", select: "id" },
  // app/(portal)/admin/members/actions.ts
  { table: "profiles", select: "id, admin_role, memberships ( tier, status )" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "profiles", select: "id, email" },
  // app/(portal)/admin/errors/actions.ts
  { table: "profiles", select: "id, email, full_name" },
  // app/api/cron/reminders/route.ts
  { table: "profiles", select: "id, email, full_name, phone" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "profiles", select: "id, full_name" },
  // app/(portal)/admin/members/page.tsx
  { table: "profiles", select: "id, full_name, email" },
  // app/(portal)/admin/members/page.tsx
  { table: "profiles", select: "id, full_name, email, title, company, phone, admin_role, admin_perms, memberships!inner ( id, tier, status, access_expires_at, source, created_at )" },
  // app/(portal)/admin/members/page.tsx
  { table: "profiles", select: "id, full_name, email, title, company, phone, admin_role, admin_perms, tester, memberships!inner ( id, tier, status, access_expires_at, source, created_at )" },
  // app/api/community/members/route.ts
  { table: "profiles", select: "id, full_name, title, company" },
  // app/(portal)/members/page.tsx
  { table: "profiles", select: "id, full_name, title, company, industry, email, phone, share_contact, memberships!inner(tier, status)" },
  // app/(portal)/search/page.tsx
  { table: "profiles", select: "id, full_name, title, company, industry, memberships!inner(tier, status)" },
  // lib/speaker-tools.ts
  { table: "profiles", select: "phone" },
  // app/(portal)/profile/page.tsx
  { table: "profiles", select: "phone, company, title, industry, bio, admin_title, stripe_customer_id, created_at" },
  // app/(portal)/profile/page.tsx
  { table: "profiles", select: "phone, company, title, industry, bio, share_contact, admin_title, stripe_customer_id, created_at" },
  // app/api/stream/token/route.ts
  { table: "profiles", select: "stream_synced_key" },
  // app/(portal)/upgrade/page.tsx
  { table: "profiles", select: "stripe_customer_id" },
  // lib/push.ts
  { table: "push_subscriptions", select: "id, endpoint, p256dh, auth" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "resource_use_counts", select: "*" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "resource_uses", select: "resource_id, used_at" },
  // lib/activity.ts
  { table: "resource_uses", select: "used_at, profiles ( full_name, email ), resources ( title )" },
  // app/(auth)/speaker-onboarding/actions.ts
  { table: "resources", select: "id" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "resources", select: "id, title" },
  // app/(portal)/admin/resources/page.tsx
  { table: "resources", select: "id, title, category, description, url, partner_name, min_access, active, image_url" },
  // lib/directory-queries.ts
  { table: "resources", select: "id, title, category, description, url, partner_name, min_access, image_url" },
  // lib/speaker-tools.ts
  { table: "resources", select: "title, description, url" },
  // app/(portal)/speaker/page.tsx
  { table: "resources", select: "title, description, url, image_url" },
  // app/(portal)/admin/resources/actions.ts
  { table: "resources", select: "url" },
  // app/api/cron/gift-activate/route.ts
  { table: "scheduled_gifts", select: "id, profile_id, email, name, tier, months, starts_at, source" },
  // lib/onboarding.ts
  { table: "scheduled_gifts", select: "id, starts_at, tier, months" },
  // app/api/cron/scheduled-posts/route.ts
  { table: "scheduled_posts", select: "id" },
  // app/api/cron/scheduled-posts/route.ts
  { table: "scheduled_posts", select: "id, channel, body" },
  // lib/services-queries.ts
  { table: "services", select: "id, name, tagline, description, url, price_label" },
  // app/(portal)/admin/services/page.tsx
  { table: "services", select: "id, name, tagline, description, url, price_label, sort_order, active" },
  // app/(portal)/speaker/page.tsx
  { table: "session_enrollment_counts", select: "session_id, enrolled" },
  // lib/sessions/invitees.ts
  { table: "session_invitees", select: "profile_id" },
  // app/api/cron/reminders/route.ts
  { table: "session_invitees", select: "session_id, profile_id" },
  // app/(portal)/library/[id]/page.tsx
  { table: "session_notes", select: "body" },
  // lib/badge-queries.ts
  { table: "session_notes", select: "profile_id, body" },
  // app/(portal)/profile/page.tsx
  { table: "session_notes", select: "session_id, body" },
  // lib/session-resources.ts
  { table: "session_resources", select: "id, name, type, url" },
  // app/(portal)/speaker/page.tsx
  { table: "session_resources", select: "id, session_id, name, type, url, sort" },
  // lib/session-resources.ts
  { table: "session_resources", select: "id, session_id, sort" },
  // lib/session-resources.ts
  { table: "session_resources", select: "id, sort" },
  // lib/session-resources.ts
  { table: "session_resources", select: "session_id" },
  // lib/session-resources.ts
  { table: "session_resources", select: "sort" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "session_speakers", select: "session_id" },
  // lib/sessions/queries.ts
  { table: "session_speakers", select: "session_id, sort, speakers!session_speakers_speaker_id_fkey ( id, name, title )" },
  // lib/speaker-tools.ts
  { table: "session_speakers", select: "speaker_id" },
  // lib/zoom-recordings.ts
  { table: "session_topics", select: "topic_id, is_primary" },
  // app/(portal)/admin/sessions/actions.ts
  { table: "sessions", select: "id" },
  // app/api/cron/attendance/route.ts
  { table: "sessions", select: "id, starts_at, duration_min, recurrence, recurrence_until" },
  // app/api/zoom/signature/route.ts
  { table: "sessions", select: "id, starts_at, duration_min, status, recurrence, recurrence_until, zoom_meeting_id, zoom_passcode, speakers!sessions_speaker_id_fkey ( profile_id, archived_at, expires_at )" },
  // app/api/cron/attendance/route.ts
  { table: "sessions", select: "id, status, starts_at, duration_min" },
  // app/api/cron/attendance/route.ts
  { table: "sessions", select: "id, status, starts_at, duration_min, recurrence, recurrence_until" },
  // app/api/cron/summaries/route.ts
  { table: "sessions", select: "id, title, ai_summaries ( id )" },
  // app/api/cron/attendance/route.ts
  { table: "sessions", select: "id, title, category, min_access, program" },
  // app/(portal)/admin/sessions/actions.ts
  { table: "sessions", select: "id, title, category, min_access, program, zoom_meeting_id" },
  // lib/sessions/queries.ts
  { table: "sessions", select: "id, title, description, category, starts_at, duration_min, capacity, min_access, status, program, recurrence, recurrence_until, host_name, restricted, speakers!sessions_speaker_id_fkey ( id, name, title, archived_at, expires_at )" },
  // lib/sessions/queries.ts
  { table: "sessions", select: "id, title, description, category, starts_at, duration_min, capacity, min_access, status, program, recurrence, recurrence_until, host_name, speakers!sessions_speaker_id_fkey ( id, name, title, archived_at, expires_at )" },
  // lib/sessions/queries.ts
  { table: "sessions", select: "id, title, description, category, starts_at, duration_min, capacity, min_access, status, speakers!sessions_speaker_id_fkey ( id, name, title )" },
  // app/api/sessions/[id]/publish/route.ts
  { table: "sessions", select: "id, title, description, starts_at, duration_min, zoom_meeting_id, status, program" },
  // app/(portal)/admin/topics/page.tsx
  { table: "sessions", select: "id, title, host_name, session_topics ( topic_id, is_primary ), speakers!sessions_speaker_id_fkey ( name )" },
  // app/api/cron/summaries/route.ts
  { table: "sessions", select: "id, title, speakers!sessions_speaker_id_fkey ( name )" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "sessions", select: "id, title, starts_at" },
  // app/api/cron/reminders/route.ts
  { table: "sessions", select: "id, title, starts_at, duration_min, recurrence, recurrence_until" },
  // app/api/cron/reminders/route.ts
  { table: "sessions", select: "id, title, starts_at, duration_min, recurrence, recurrence_until, restricted" },
  // app/page.tsx
  { table: "sessions", select: "id, title, starts_at, speakers!sessions_speaker_id_fkey ( name )" },
  // app/api/cron/monthly-report/route.ts
  { table: "sessions", select: "id, title, status, starts_at, program" },
  // app/api/cron/attendance/route.ts
  { table: "sessions", select: "id, zoom_meeting_id, starts_at, duration_min, status" },
  // app/api/cron/attendance/route.ts
  { table: "sessions", select: "id, zoom_meeting_id, starts_at, duration_min, status, recurrence, recurrence_until" },
  // app/(portal)/admin/sessions/actions.ts
  { table: "sessions", select: "id, zoom_meeting_id, status" },
  // app/(portal)/admin/speakers/page.tsx
  { table: "sessions", select: "speaker_id" },
  // app/(portal)/speaker/actions.ts
  { table: "sessions", select: "title" },
  // lib/sessions/queries.ts
  { table: "sessions", select: "zoom_join_url, zoom_meeting_id" },
  // app/(portal)/admin/sessions/actions.ts
  { table: "sessions", select: "zoom_meeting_id" },
  // app/(portal)/admin/sessions/actions.ts
  { table: "sessions", select: "zoom_meeting_id, starts_at, duration_min" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "speaker_invites", select: "email" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "speaker_invites", select: "id" },
  // app/(portal)/admin/speakers/page.tsx
  { table: "speaker_invites", select: "id, email, display_name, created_at" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "speakers", select: "*" },
  // app/api/stream/token/route.ts
  { table: "speakers", select: "expires_at, archived_at" },
  // app/(auth)/speaker-onboarding/actions.ts
  { table: "speakers", select: "id" },
  // lib/current-member.ts
  { table: "speakers", select: "id, archived_at, expires_at, name, title, bio, industries, resource_id" },
  // app/api/bridge/profile/route.ts
  { table: "speakers", select: "id, links" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "speakers", select: "id, name, profile_id" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "speakers", select: "id, name, profile_id, contact_email" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "speakers", select: "id, name, profile_id, contact_email, archived_at" },
  // app/(portal)/community/actions.ts
  { table: "speakers", select: "id, name, profile_id, expires_at, archived_at" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "speakers", select: "id, name, profile_id, title, bio, headshot_url, website, industries, tsls_main_speaker" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "speakers", select: "id, name, profile_id, title, bio, headshot_url, website, industries, tsls_main_speaker, contact_email" },
  // app/(portal)/speaker/page.tsx
  { table: "speakers", select: "id, name, title" },
  // lib/speaker-tools.ts
  { table: "speakers", select: "id, name, title, bio, industries, website, headshot_url, resource_id, expires_at, archived_at" },
  // lib/speaker-tools.ts
  { table: "speakers", select: "id, name, title, bio, industries, website, headshot_url, resource_id, expires_at, archived_at, speaker_month, tsls_main_speaker" },
  // lib/speaker-tools.ts
  { table: "speakers", select: "id, name, title, bio, industries, website, headshot_url, resource_id, expires_at, archived_at, speaker_month, tsls_main_speaker, payment_access" },
  // lib/speaker-tools.ts
  { table: "speakers", select: "id, name, title, bio, industries, website, headshot_url, resource_id, expires_at, archived_at, speaker_month, tsls_main_speaker, payment_access, organization, featured_session_date, featured_session_time, advisor_agreement_waived" },
  // app/(portal)/admin/agreement/page.tsx
  { table: "speakers", select: "id, name, tsls_main_speaker, advisor_agreement_waived" },
  // app/(auth)/speaker-onboarding/actions.ts
  { table: "speakers", select: "id, resource_id" },
  // lib/agreement-doc-db.ts
  { table: "speakers", select: "id, tsls_main_speaker, advisor_agreement_waived" },
  // lib/revenue.ts
  { table: "speakers", select: "id, tsls_main_speaker, archived_at, expires_at" },
  // lib/revenue.ts
  { table: "speakers", select: "id, tsls_main_speaker, payment_access, archived_at, expires_at" },
  // app/(auth)/speaker-onboarding/actions.ts
  { table: "speakers", select: "name" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "speakers", select: "profile_id" },
  // app/(portal)/members/page.tsx
  { table: "speakers", select: "profile_id, expires_at, archived_at" },
  // app/(portal)/admin/speakers/actions.ts
  { table: "speakers", select: "profile_id, resource_id" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "sponsor_event_counts", select: "*" },
  // lib/activity.ts
  { table: "sponsor_events", select: "at, kind, profiles ( full_name, email ), sponsors ( name )" },
  // app/api/cron/reconcile/route.ts
  { table: "sponsor_events", select: "id" },
  // app/api/sponsors/track/route.ts
  { table: "sponsor_events", select: "sponsor_id" },
  // app/(portal)/admin/sponsors/page.tsx
  { table: "sponsor_events", select: "sponsor_id, kind" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "sponsor_events", select: "sponsor_id, kind, at" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsor_invites", select: "id" },
  // app/(portal)/admin/sponsors/page.tsx
  { table: "sponsor_invites", select: "id, email, tier, business_name, created_at" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsor_invites", select: "invited_profile_id" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsor_members", select: "profile_id" },
  // lib/sponsor-team.ts
  { table: "sponsor_members", select: "profile_id, role" },
  // app/(portal)/admin/members/page.tsx
  { table: "sponsor_members", select: "profile_id, sponsor_id, role" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsor_members", select: "profile_id, sponsors!inner ( archived_at, expires_at )" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsor_members", select: "role" },
  // app/(portal)/admin/sponsors/page.tsx
  { table: "sponsor_members", select: "sponsor_id, profile_id, profiles ( full_name, email )" },
  // app/(portal)/admin/members/actions.ts
  { table: "sponsor_members", select: "sponsor_id, role" },
  // app/(portal)/sponsor/actions.ts
  { table: "sponsor_members", select: "sponsor_id, sponsors!inner ( archived_at, expires_at )" },
  // app/expired/page.tsx
  { table: "sponsor_members", select: "sponsors ( name, expires_at, archived_at )" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsor_tiers", select: "value" },
  // lib/tier-catalog.ts
  { table: "sponsor_tiers", select: "value, label, price, in_kind, available, sold_out, vip_tickets, highlights, active, sort" },
  // app/(auth)/sponsor-onboarding/actions.ts
  { table: "sponsors", select: "id" },
  // app/(portal)/sponsor/actions.ts
  { table: "sponsors", select: "id, expires_at" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "sponsors", select: "id, name" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsors", select: "id, name, logo_url" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsors", select: "id, name, logo_url, website" },
  // app/(portal)/sponsor/page.tsx
  { table: "sponsors", select: "id, name, tier, tagline, description, offer, website, expires_at, archived_at, logo_url, sidebar_ad_url" },
  // app/(portal)/admin/sponsors/page.tsx
  { table: "sponsors", select: "id, name, tier, tagline, description, offer, website, logo_url, sidebar_ad_url, rail_active, expires_at, archived_at" },
  // app/(portal)/admin/sponsors/page.tsx
  { table: "sponsors", select: "id, name, tier, tagline, description, offer, website, logo_url, sidebar_ad_url, rail_active, expires_at, archived_at, prospect, contact_name, contact_email, contact_phone, notes" },
  // app/(portal)/admin/sponsors/page.tsx
  { table: "sponsors", select: "id, name, tier, tagline, offer, website, logo_url, sidebar_ad_url, rail_active, expires_at, archived_at" },
  // app/(portal)/admin/sponsors/page.tsx
  { table: "sponsors", select: "id, ticket_override" },
  // app/(portal)/sponsor/actions.ts
  { table: "sponsors", select: "name" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsors", select: "name, logo_url" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsors", select: "name, tier, tagline, description, website, logo_url, prospect, archived_at" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsors", select: "tier" },
  // app/(portal)/admin/sponsors/actions.ts
  { table: "sponsors", select: "tier, prospect" },
  // lib/sponsor-team.ts
  { table: "sponsors", select: "tier, ticket_override" },
  // app/(portal)/dashboard/testimonial-actions.ts
  { table: "testimonials", select: "id" },
  // lib/testimonials.ts
  { table: "testimonials", select: "id, name, role_company, quote" },
  // app/(portal)/admin/testimonials/page.tsx
  { table: "testimonials", select: "id, name, role_company, quote, status, created_at" },
  // app/(portal)/dashboard/testimonial-actions.ts
  { table: "testimonials", select: "id, status" },
  // lib/tiers.ts
  { table: "tier_features", select: "tier_slug, feature_key, allowed" },
  // lib/tsls-intake-db.ts
  { table: "tsls_speaker_intake", select: "answers, signed_name, signed_date, form_version, submitted_at, updated_at" },
  // lib/tsls-intake-db.ts
  { table: "tsls_speaker_intake", select: "speaker_id, submitted_at, updated_at" },
  // app/(portal)/library/[id]/page.tsx
  { table: "video_notes", select: "body" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "video_view_counts", select: "*" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "video_views", select: "video_id, profile_id, watched_at" },
  // lib/activity.ts
  { table: "video_views", select: "watched_at, profiles ( full_name, email ), videos ( title )" },
  // app/(portal)/admin/videos/actions.ts
  { table: "videos", select: "id" },
  // app/(portal)/speaker/actions.ts
  { table: "videos", select: "id, session_id, sessions!inner ( speaker_id )" },
  // app/(portal)/admin/analytics/page.tsx
  { table: "videos", select: "id, title" },
  // app/(portal)/admin/videos/page.tsx
  { table: "videos", select: "id, title, category, mux_playback_id, thumbnail_url, duration_sec, min_access, published_at" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, mux_playback_id, thumbnail_url, duration_sec, min_access, published_at, session_id, sessions ( speakers!sessions_speaker_id_fkey ( name ) )" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, mux_playback_id, thumbnail_url, duration_sec, min_access, published_at, session_id, sessions ( speakers!sessions_speaker_id_fkey ( name ), ai_summaries ( takeaways, quotes, action_items, highlights, model, generated_at ) ), ai_summaries!video_id ( takeaways, quotes, action_items, highlights, model, generated_at )" },
  // app/(portal)/speaker/page.tsx
  { table: "videos", select: "id, title, category, published_at" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, season, video_topics ( is_primary, content_topics ( id, name, slug ) ), mux_playback_id, thumbnail_url, duration_sec, min_access, published_at, session_id, sessions ( speakers!sessions_speaker_id_fkey ( name ) )" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, season, video_topics ( is_primary, content_topics ( id, name, slug ) ), mux_playback_id, thumbnail_url, duration_sec, min_access, published_at, session_id, sessions ( speakers!sessions_speaker_id_fkey ( name ), ai_summaries ( takeaways, quotes, action_items, highlights, model, generated_at ) ), ai_summaries!video_id ( takeaways, quotes, action_items, highlights, model, generated_at )" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, season, video_topics ( is_primary, content_topics ( id, name, slug ) ), thumbnail_url, duration_sec, min_access, published_at, sessions ( speakers!sessions_speaker_id_fkey ( name ) )" },
  // lib/videos/queries.ts
  { table: "videos", select: "id, title, category, thumbnail_url, duration_sec, min_access, published_at, sessions ( speakers!sessions_speaker_id_fkey ( name ) )" },
  // app/api/cron/summaries/route.ts
  { table: "videos", select: "id, title, min_access, mux_playback_id, published_at, session_id, ai_summaries!video_id ( id ), sessions ( ai_summaries ( id ) )" },
  // app/api/cron/summaries/route.ts
  { table: "videos", select: "id, title, mux_asset_id, mux_playback_id, duration_sec, published_at, session_id, ai_summaries!video_id ( id ), sessions ( ai_summaries ( id ) )" },
  // app/(portal)/admin/topics/page.tsx
  { table: "videos", select: "id, title, session_id, video_topics ( topic_id, is_primary ), sessions ( speakers!sessions_speaker_id_fkey ( name ) )" },
  // app/(portal)/library/[id]/page.tsx
  { table: "videos", select: "mux_asset_id" },
  // app/(portal)/admin/videos/actions.ts
  { table: "videos", select: "published_at" },
  // app/api/cron/attendance/route.ts
  { table: "videos", select: "session_id" },
  // app/(portal)/admin/education/actions.ts
  { table: "videos", select: "title, session_id, ai_summaries!video_id ( takeaways, quotes, action_items, highlights )" },
];
